#pragma config(Sensor, S3,     Colour,         sensorEV3_Color, modeEV3Color_Ambient)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const bool threshold = 500;
const float cmdSpace = 1;
const float shortLongBorder = 0.2;

task main()
{
	bool pre = false;
	bool now = pre;
	resetTimer(T1);
	while (true)
	{
		now = check();
		if (now!=pre) // detect rising edge
		{
			float sinceLast = getTimer(T1,seconds);
			resetTimer(T1);
			if (sinceLast>cmdSpace)
			{
				newCmd();
			} else if (sinceLast>=shortLongBorder)
			{
				addShortSignal();
			} else {
				addLongSignal();
			}
		}
		pre = now;
		sleep(1);
	}
}

bool check()
{
	return SensorValue[Colour]>threshold;
}

void newCmd()
{
	//NotImplemented
}

void addShortSignal()
{
	//NotImplemented
}

void addLongSignal()
{
	//NotImplemented
}
