#pragma config(Sensor, S3,     Colour,         sensorEV3_Color, modeEV3Color_Ambient)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int threshold = 10;
const int cmdSpace = 10000;
const int shortLongBorder = 2000;

const int morseTable[8][6] =
{
	{0,1,-1,-1,-1,-1}, 	// a
	{1,0,0,0,-1,-1},   	// b
	{1,0,1,0,-1,-1},		// c
	{1,0,0,-1,-1,-1},		// d
	{0,-1,-1,-1,-1,-1},	// e
	{0,0,1,0,-1,-1},		// f
	{1,1,0,-1,-1,-1},		// g
	{0,0,0,0,-1,-1}			// h
};

bool buffer[6];
int added = 0;

bool checkSensor()
{
	return SensorValue[Colour]>threshold;
}

void newCmd()
{
	//NotImplemented
	int cmd = -1;
	for (int c = 0; c<8; c++)
	{
		bool isInvalid;
		for (int s = 0; s<6; s++)
		{
			isInvalid |= !(morseTable[c][s] == buffer[s] || morseTable[c][s] == -1);
		}
		if (!isInvalid)
		{
			cmd = c;
			break;
		}
	}
	char str[15];
	sprintf(str, "%d", cmd);
	//displayCenteredBigTextLine(4, str);

	memset(&buffer[0], 0, sizeof(buffer));
	added = 0;
}

void addSignal(bool isLong)
{
	buffer[added++] = isLong;
}

task main()
{
	bool pre = false;
	bool now = pre;
	while (true)
	{
		now = checkSensor();
		if (now!=pre && now) // detect rising edge
		{
			int sinceLast = time1[T1];
			clearTimer(T1);
			if (sinceLast>cmdSpace || added==6-1) {
				newCmd();
			} else {
				addSignal( sinceLast>shortLongBorder );
			}
			char str[15];
			sprintf(str, "%d", sinceLast);
			displayCenteredBigTextLine(4, str);
		}
		pre = now;
		sleep(1);
	}
}
